[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[dependencies]
forge-std = "1.9.3"
solady = "0.0.253"
"@openzeppelin-contracts" = "5.1.0-rc.0"

[soldeer]

remappings_version = false
remappings_location = "txt"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
